import type { Metadata } from "next";
import "./globals.css";
import Footer from "../components/ui/Landing/Footer";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Muebleria EDSI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <ClerkProvider>
        <body className="bg-white">
          {children}
          <Footer />
        </body>
      </ClerkProvider>
    </html>
  );
}
